server:
  port: 8888
#  servlet:
#    context-path: /test
spring:
  application:
    name: demo-application
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    username:
    password:
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/index-test?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000


  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

#  profiles:
#    active: test

mybatis:
  mapper-locations: classpath*:/mapper/**.xml
  executor-type: simple # 默认 simple 类型
  configuration:
#    object-factory: DefaultObjectFactory
    cache-enabled: true # 二级缓存，默认开启。还需要在指定Mapper中开启cache 配置
  lazy-initialization: false
  mapper-default-scope:



# dubbo
dubbo:
  # The default value of dubbo.application.name is ${spring.application.name}
  application:
    name: ${spring.application.name}
  scan:
    # dubbo服务发布者所在的包、   dubbo服务调用者所在的包
    base-packages: example.rpc.dubbo.test02.service
  registry:
    address: 127.0.0.1  # zookeeper注册中心的地址 N/A
    port: 2181          # zookeeper注册中心的端口
  # 服务发布者增加信息
  protocol:
    name: dubbo
    port: 12345
#    serialization:
  provider:
    retries: 0          # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试
  # 服务调用者增加
  consumer:
    timeout: 1000
    check: true         # 服务启动时检查被调用服务是否可用
    retries: 2          # 服务调用重试次数

management:
  endpoint:
    health:
      show-details: always
    startup:
      enabled: on
  endpoints:
    web:
      exposure:
        include: '*'
  health:
#    defaults:
#      enabled: false
    elasticsearch:
      enabled: off
    redis:
      enabled: off



