server:
  port: 8080
#  servlet:
#    context-path: /test
spring:
  transaction:
    custom-time-out: 1000 # 通过配置设定超时时间
  application:
    name: demo-application
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/index-test?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000


  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  aop:
    proxy-target-class: false

#  profiles:
#    active: test

mybatis:
  mapper-locations: classpath*:/mapper/**.xml
  executor-type: simple # 默认 simple 类型
  configuration:
#    object-factory: DefaultObjectFactory
    cache-enabled: true # 二级缓存，默认开启。还需要在指定Mapper中开启cache 配置
  lazy-initialization: false
  mapper-default-scope:


management:
  endpoint:
    health:
      show-details: always
    startup:
      enabled: on
  endpoints:
    web:
      exposure:
        include: '*'



